### ISSUE TITLE
side bar, status bar not visible

### ISSUE THREAD

**Issue by xainbutt** [christopherburton/Jeffrey-Way-Theme#10]
i have follow the instructions but nothing working as expected..side bar and status bar not visible..and i cant even explain about the tabs..
![desctop screenshot](https://cloud.githubusercontent.com/assets/11776307/15997479/e83c8ac6-314d-11e6-8d6f-5f8668790ab1.png)

**Comment by christopherburton** [comment]
Have you tried this?: https://github.com/christopherburton/Jeffrey-Way-Theme/issues/5#issuecomment-214500693

**Comment by xainbutt** [comment]
yes already tried a couple times but no changes..i dont why..i have checked every thing that came to my mind..

**Comment by christopherburton** [comment]
Perhaps this week we can schedule a one-on-one to solve your issue.
