### ISSUE TITLE
Git icon missing

### ISSUE THREAD

**Issue by SebJansen** [christopherburton/Jeffrey-Way-Theme#11]
## This is the gitginore file looks in one of Jeffrey's Laracast videos
<img width="191" alt="screen shot 2016-06-25 at 20 13 28" src="https://cloud.githubusercontent.com/assets/9006306/16364476/392d5510-3be8-11e6-84b2-8c0f779b80fd.png">

## ...and this is how it looks for me
<img width="219" alt="screen shot 2016-06-25 at 20 13 54" src="https://cloud.githubusercontent.com/assets/9006306/16364477/394f659c-3be8-11e6-8857-4502cf3ada96.png">

**Comment by christopherburton** [comment]
Weird. I'll have to look into this ASAP.

**Comment by christopherburton** [comment]
Please keep an eye on https://github.com/equinusocio/material-theme/issues/890

**Comment by christopherburton** [comment]
Fixed: https://github.com/equinusocio/material-theme/commit/bffa1f825013619c95d16851af22150373f3dcc8

**Comment by oivva** [comment]
@christopherburton Now you can use [File Icons Extended](https://packagecontrol.io/packages/File%20Icons%20Extended) that supports Material Theme.

**Comment by christopherburton** [comment]
Solved: https://github.com/equinusocio/material-theme/issues/890#issuecomment-246725022
