### ISSUE TITLE
Customise font ?

### ISSUE THREAD

**Issue by barbuslex** [christopherburton/Jeffrey-Way-Theme#13]
Hi,

Can you configure you custom Input font here : http://input.fontbureau.com/preview/
Can you send us the customised url generated ?

Thanks

**Comment by christopherburton** [comment]
@barbuslex Sorry for the late reply. Hope this helps.

http://input.fontbureau.com/preview/?size=14&language=python&theme=solarized-dark&family=InputSans&width=300&weight=300&line-height=1.6&a=0&g=0&i=serif&l=serif&zero=0&asterisk=0&braces=0&preset=default&customize=please
