### ISSUE TITLE
Material-Theme not working

### ISSUE THREAD

**Issue by lperry65** [christopherburton/Jeffrey-Way-Theme#15]
I'm using Sublime Text 3 ( Build 3126 ) on Windows 10, the colour scheme works fine but when I add the theme option the UI looses it's colours and the sidebar goes black. Also things like search (CTRL + F) the buttons lose styling and don't work.

**Comment by christopherburton** [comment]
> when I add the theme option

What theme option?

**Comment by lperry65** [comment]
This theme option:
"theme": "Material-Theme.sublime-theme",

**Comment by christopherburton** [comment]
After saving your settings, what happens when you exit Sublime and restart the program? Is it still black?
