### ISSUE TITLE
Parts of line of code are not the right colors.

### ISSUE THREAD

**Issue by Gino** [christopherburton/Jeffrey-Way-Theme#16]
Hello,

When I look at the screenshot that you posted in your readme, I see that when I do the following code, the part **AuthController** should be the same yellow as the part: **Controller**
![..](http://i.imgur.com/bOGrWwZ.png)

Also the parameter in a public function is not the same color as it should be, how can I all change those colors for specific things?:
![..](http://i.imgur.com/ei2J1qH.png)

The parameter should have this color:
![..](http://i.imgur.com/TYA6cQu.png)

Is there a way that I can do this?

Thank you.

**Comment by christopherburton** [comment]
Are you saying that it **should** be that color or that you **want** that color?

**Comment by tushiee** [comment]
Both, they are not the colors that I want. And I have no idea how to change those parts.

**Comment by christopherburton** [comment]
@tushiee [This](https://github.com/christopherburton/Jeffrey-Way-Theme/blob/master/schemes/Facebook.tmTheme) is the file you would need to edit. Hope that helps.

**Comment by christopherburton** [comment]
I just realized that there does seem to be an issue with syntax highlighting when I compared this repo's screenshots to my local project. However, I can't seem to narrow it down at the moment.

**Comment by christopherburton** [comment]
Fixed. https://github.com/christopherburton/Jeffrey-Way-Theme/commit/460f85c8352cdc97466b4cf385a56e50ec90506a
