### ISSUE TITLE
cannot find Edit Material-Theme-Darker.sublime-theme

### ISSUE THREAD

**Issue by roelvan** [christopherburton/Jeffrey-Way-Theme#4]
Where can i find this file so i can edit it? Thanks for this theme!

**Comment by arneetsingh** [comment]
same issue,can't find any such file?

**Comment by christopherburton** [comment]
@roelvan @arneetsingh I've added the file on the master page. Just download it and inside the Jeffrey-Way theme folder.

**Comment by arneetsingh** [comment]
And at what location should I put this file.

**Comment by christopherburton** [comment]
In Sublime: Preferences > Browse Packages > Jeffrey Way Theme (inside this folder)

**Comment by arneetsingh** [comment]
Its not working.Appretiate if you could help. http://i.imgur.com/zBnBPX0.jpg

**Comment by christopherburton** [comment]
@arneetsingh What happens if you CMD+Q and re-open Sublime?

**Comment by arneetsingh** [comment]
Tried it.Still no luck.
Could you share your working set of theme files.

**Comment by christopherburton** [comment]
@arneetsingh Do you have gmail?

**Comment by arneetsingh** [comment]
arneetsingh@gmail.com

**Comment by christopherburton** [comment]
I'm sending you an invite to chat. Be on the lookout.

**Comment by roelvan** [comment]
I don't see that Jeffrey Way Theme folder. According to the readme there is never an instruction to install such a package. Only the Material one and the Facebook one.

Or is this a folder I should make myself?

**Comment by christopherburton** [comment]
@roelvan I'll be rewriting the instructions as they are a bit confusing.

**Comment by christopherburton** [comment]
@roelvan Please see new install directions. Should be far more simple now.

**Comment by roelvan** [comment]
@christopherburton thanks, that is indeed quite easier to install now.
