### ISSUE TITLE
 Unable to open Packages/Jeffrey Way Theme/widgets/default/Widget - Material-Theme.stTheme

### ISSUE THREAD

**Issue by NicolaeCasir** [christopherburton/Jeffrey-Way-Theme#5]
Hello. I get this error(... 
Error loading colour scheme Packages/Jeffrey Way Theme/widgets/default/Widget - Material-Theme.stTheme: Unable to open Packages/Jeffrey Way Theme/widgets/default/Widget - Material-Theme.stTheme
![screen shot 2016-04-25 at 9 09 40 pm](https://cloud.githubusercontent.com/assets/8903698/14793936/148712c6-0b2a-11e6-9aa8-7fc3c4d06e2c.png)

**Comment by christopherburton** [comment]
Thank you. Working on the issue right now. I'll get back to you as soon as
possible. Please be aware that we may have to chat one-on-one for me to
resolve this problem. Thanks again.

**Comment by christopherburton** [comment]
@NicolaeCasir I noticed you did not rename the folder from `Jeffrey-Way-Theme-master` to `Jeffrey Way Theme`. Can you try this for me?

**Comment by NicolaeCasir** [comment]
Now its OK. I renamed.. but now i can't see sidebar(opened files((()

![screen shot 2016-04-25 at 9 33 13 pm](https://cloud.githubusercontent.com/assets/8903698/14794551/64c305ee-0b2d-11e6-8993-c454d20be440.png)

**Comment by christopherburton** [comment]
@NicolaeCasir Did you press `CMD+Q` Sublime? Then reopen to see if the problem persists.

**Comment by NicolaeCasir** [comment]
@christopherburton Yes,... few times.. and nothing

**Comment by NicolaeCasir** [comment]
@christopherburton  without `"theme": "Material-Theme.sublime-theme"`, it's ok.. with default theme but with your colour sheme... but i want this theme..
![screen shot 2016-04-25 at 9 38 52 pm](https://cloud.githubusercontent.com/assets/8903698/14794779/38c674b6-0b2e-11e6-929e-6810363c1971.png)

**Comment by christopherburton** [comment]
Go to **Preferences > Browse Packages**. Open the Jeffrey Way Theme folder and send over a screenshot for me. I'd like to see what's inside.

**Comment by NicolaeCasir** [comment]
@christopherburton 
![screen shot 2016-04-25 at 9 42 59 pm](https://cloud.githubusercontent.com/assets/8903698/14794897/b91eb68c-0b2e-11e6-82de-ffad8f61572a.png)

**Comment by christopherburton** [comment]
Copy the name of the Material exec file and paste it in your settings by theme. Does that help?

**Comment by christopherburton** [comment]
Also, if you have a package/plugin called `SyncedSidebarBg`, you need to disable that.

**Comment by NicolaeCasir** [comment]
It's the same but if I rename `Material-Theme.sublime-theme` to `Packages/Jeffrey Way Theme/Material-Theme.sublime-theme` I get few icons (screen 2)
![screen shot 2016-04-25 at 9 48 40 pm](https://cloud.githubusercontent.com/assets/8903698/14795116/af74dc8c-0b2f-11e6-9585-5b73491027ac.png)
![screen shot 2016-04-25 at 9 48 53 pm](https://cloud.githubusercontent.com/assets/8903698/14795120/b3428ec2-0b2f-11e6-8f17-61137a8f1677.png)

**Comment by NicolaeCasir** [comment]
I do not have plugins installed.

**Comment by christopherburton** [comment]
Go to **Preferences > Color Scheme > Jeffrey Way Theme > schemes** and choose Facebook. Let me know the result.

**Comment by NicolaeCasir** [comment]
It is active! 
![screen shot 2016-04-25 at 9 53 47 pm](https://cloud.githubusercontent.com/assets/8903698/14795240/3c82d6a6-0b30-11e6-8eee-ecd571bfc5fc.png)

P.S. Shall i reinstall Sublime?

**Comment by christopherburton** [comment]
Make sure you quit the program each time you change the settings. Otherwise it may not work.

If that also does nothing to resolve the issue, try copying my settings as seen [here](https://github.com/christopherburton/Jeffrey-Way-Theme/issues/6).

**Comment by NicolaeCasir** [comment]
Nothing. I have Beta license. It is a problem?

**Comment by christopherburton** [comment]
I doubt it. Would you feel comfortable doing a TeamViewer? Basically I would control your computer and install it for you. You are able to watch me and terminate the session at any time if you feel uncomfortable. Other than this I'm not sure what else I can suggest to help resolve the problem.

**Comment by NicolaeCasir** [comment]
No problem... 
224 083 178
5997

**Comment by christopherburton** [comment]
**Solution**

Download the Material Theme zip, unzip and add it to `Preferences > Packages`.

Now, go to `Preferences > Color Scheme` and choose the Material Theme. Then follow this repo's directions.
