### ISSUE TITLE
Rename (bottom panel) is unreadable

### ISSUE THREAD

**Issue by SebJansen** [christopherburton/Jeffrey-Way-Theme#7]
# Editing file #
This is how it looks while I'm renaming a file. Bottom panel is quite invisible.
<img width="1072" alt="screen shot 2016-05-04 at 18 28 04" src="https://cloud.githubusercontent.com/assets/9006306/15021252/141ad734-1226-11e6-90ae-bd48e6a0ad87.png">
# Not editing file #
To show how invisible the bottom panel is.
<img width="1072" alt="screen shot 2016-05-04 at 18 28 06" src="https://cloud.githubusercontent.com/assets/9006306/15021254/1467b6d0-1226-11e6-992c-4092a65fc439.png">
# Standard readability #
As can be seen, the panel that is opened while a file is renamed is quite readable.
<img width="1072" alt="screen shot 2016-05-04 at 18 28 32" src="https://cloud.githubusercontent.com/assets/9006306/15021253/145887d2-1226-11e6-9e55-212e41b72a95.png">
# My settings #
In case their the root cause.
```
{
	"auto_complete": true,
	"auto_complete_commit_on_tab": true,
	"auto_complete_with_fields": true,
	"bold_folder_labels": true,
	"color_scheme": "Packages/User/SublimeLinter/Facebook (SL).tmTheme",
	"default_encoding": "UTF-8",
	"detect_indentation": true,
	"font_face": "Menlo",
	"folder_exclude_patterns":
	[
		".git",
		".gitignore",
		".bundle",
		".sass-cache"
	],
	"font_options":
	[
		"subpixel_antialias"
	],
	"highlight_line": true,
	"highlight_modified_tabs": true,
	"ignored_packages":
	[
		"Vintage"
	],
	"line_padding_bottom": 8,
	"line_padding_top": 8,
	"tab_size": 4,
	"theme": "Material-Theme.sublime-theme",
	"translate_tabs_to_spaces": true,
	"trim_trailing_white_space_on_save": true,
	"word_wrap": true
}
```
# Solution? #
I think the fastest solution would be to change the text colour to #FFF. So that the filename that's being edited is readable. Unfortunately I haven't found the attribute in 774-lined theme file :'(
Help is much appreciated. This theme looks really good!
<img width="1072" alt="screen shot 2016-05-04 at 18 37 53" src="https://cloud.githubusercontent.com/assets/9006306/15021471/565b6022-1227-11e6-89ac-f3d303c6935b.png">

**Comment by SebJansen** [comment]
##### Oh. I just found the (temporary) solution, which is illustrated in this gif. #####
![a0dd09c0-1412-11e5-8ecf-f7f9ade439ae](https://cloud.githubusercontent.com/assets/9006306/15021578/ee406086-1227-11e6-9504-8c1d7887c1d2.gif)

**Comment by christopherburton** [comment]
The creator of the Material states this is a bug in ST3, I believe. I'm not
home at the moment so I'd have to check again.
