### ISSUE TITLE
Material theme not working

### ISSUE THREAD

**Issue by matevisky** [christopherburton/Jeffrey-Way-Theme#9]
I have some issue with install the package. I have been stared from the begining but it is not working:
http://pasteboard.co/1fZ2Kgsp.png

It seems the material theme is not get loaded. The color scheme does, and also I have been followed up the instruction with renaming the folder, but still get stucked...

Ofc If I isntall the material design paralel, it is getting work, but that is a different installation what we have in the package I guess...

Kindly ask to advice

**Comment by christopherburton** [comment]
You have to install the Material theme, first, before installing this
theme. Please check the issues and one of them should describe this same
problem.
